### ISSUE TITLE
could the source code be published?

### ISSUE THREAD

**Issue by py0ker** [jiarong0907/NetWarden#1]
I have read the paper "NetWarden: Mitigating Network Covert Channels while Preserving Performance" and would like to do some research on it. could u upload the source codes? thanks

**Comment by jiarong0907** [comment]
Thank you for your interest in our work. We are working on cleaning the code now. It should be available very soon. Please wait for a few more days. Thanks!

**Comment by py0ker** [comment]
thank you very much!
